// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Midterm_PROG3340_RDooley.Data;

#nullable disable

namespace Midterm_PROG3340_RDooley.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Midterm_PROG3340_RDooley.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RentalPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Heavy Machinery",
                            Condition = "New",
                            CreatedAt = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Large hydraulic excavator for heavy lifting",
                            IsAvailable = true,
                            Name = "Excavator",
                            RentalPrice = 250.0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Power Tools",
                            Condition = "Exellent",
                            CreatedAt = new DateTime(2022, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "18V battery-powered drill for versatile use",
                            IsAvailable = true,
                            Name = "Cordless Drill",
                            RentalPrice = 15.0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Vehicles",
                            Condition = "Fair",
                            CreatedAt = new DateTime(2021, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4x4 truck for transporting equipment",
                            IsAvailable = false,
                            Name = "Pickup Truck",
                            RentalPrice = 80.0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Safety",
                            Condition = "Poor",
                            CreatedAt = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-impact protective helmet",
                            IsAvailable = true,
                            Name = "Safety Helmet",
                            RentalPrice = 5.0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Surveying",
                            Condition = "Good",
                            CreatedAt = new DateTime(2023, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Precision surveying instrument for angle measurements",
                            IsAvailable = false,
                            Name = "Theodolite",
                            RentalPrice = 40.0
                        },
                        new
                        {
                            Id = 6,
                            Category = "Power Tools",
                            Condition = "New",
                            CreatedAt = new DateTime(2022, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gas-powered chainsaw for tree cutting",
                            IsAvailable = true,
                            Name = "Chainsaw",
                            RentalPrice = 25.0
                        },
                        new
                        {
                            Id = 7,
                            Category = "Heavy Machinery",
                            Condition = "Fair",
                            CreatedAt = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electric forklift for warehouse operations",
                            IsAvailable = true,
                            Name = "Forklift",
                            RentalPrice = 120.0
                        });
                });

            modelBuilder.Entity("Midterm_PROG3340_RDooley.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "password",
                            Role = "amdin",
                            UserName = "AdminOne"
                        },
                        new
                        {
                            Id = 2,
                            Password = "password",
                            Role = "user",
                            UserName = "UserOne"
                        },
                        new
                        {
                            Id = 3,
                            Password = "password",
                            Role = "user",
                            UserName = "UserTwo"
                        },
                        new
                        {
                            Id = 4,
                            Password = "password",
                            Role = "user",
                            UserName = "UserThree"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
